version: "3.2"
services:
  parity:
    image: makerdao/testchain-pymaker:unit-testing
    container_name: parity-test
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    user: root
    working_dir: /home/parity

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8555:8555"
    expose:
      - "8555"
    command: "--gasLimit 10000000 -p 8555 --account=\"0x91cf2cc3671a365fcbf38010ff97ee31a5b7e674842663c56769e41600696ead,1000000000000000000000000\""
    depends_on:
      - parity